constrained_ik_solver:
  manipulator:
    allow_joint_convergence: false
    allow_primary_normalization: true
    allow_auxiliary_nomalization: true
    limit_primary_motion: true
    limit_auxiliary_motion: true
    limit_auxiliary_interations: false
    solver_max_iterations: 100
    solver_min_iterations: 0
    auxiliary_max_iterations: 5
    auxiliary_max_motion: 0.5
    primary_max_motion: 2.0
    primary_norm: 1.0
    auxiliary_norm: 0.15
    primary_gain: 1.0
    auxiliary_gain: 1.0
    joint_convergence_tol: 0.0001
    constraints:
    -
      class: constrained_ik/GoalPosition
      primary: true
      weights: [1.0, 1.0, 1.0]
      position_tolerance: 0.001
      debug: true
    -
      class: constrained_ik/AvoidObstacles
      primary: false
      debug: false
      link_names:         [ shoulder_link, upper_arm_link, forearm_link, wrist_1_link, wrist_2_link, wrist_3_link]
      amplitude:          [      0.000001,       0.000001,     0.000001,     0.000001,     0.000001,     0.000001]
      minimum_distance:   [         0.001,           0.01,         0.01,         0.01,         0.01,        0.001]
      avoidance_distance: [           0.1,            0.1,          0.1,          0.1,          0.1,         0.01]
      weights:            [             1,              1,            1,            1,            1,            1]

constrained_ik_planner:
  translational_discretization_step: 0.02
  orientational_discretization_step: 0.02
  joint_discretization_step: 0.02
